# Generated by Django 5.0.3 on 2024-08-07 13:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_detail',
            name='age',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
