# Generated by Django 5.1 on 2024-08-14 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_detail_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_detail',
            name='residence',
            field=models.CharField(choices=[('alone', '자취'), ('home', '본가'), ('dormitory', '기숙사')], default='alone', max_length=10, verbose_name='거주지'),
        ),
    ]
