# Generated by Django 5.1 on 2024-08-14 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_detail_residence'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_detail',
            name='gender',
            field=models.CharField(choices=[('female', '여자'), ('male', '남자'), ('ect', '기타')], default='ect', max_length=6, verbose_name='성별'),
        ),
    ]
