# Generated by Django 5.0.7 on 2024-08-06 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_cookmethod_post_cooktime_post_ingredient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
    ]
